import {
  Zap,
  Bot,
  Database,
  Mail,
  Globe,
  Shield,
  MessageSquare,
  Clock,
  Lock,
  AlertTriangle,
  Settings,
  PhoneCall,
  Send,
  MessageCircle,
  PlayCircle,
  CheckCircle,
  XCircle,
  Shuffle,
  Play,
  Pause,
  Plus,
  Edit2,
  Trash2,
  Box,
  Tag,
  Code2,
  Users,
  Activity,
  Network,
  X,
  Save,
  Power,
  Search,
  Workflow,
  GitFork,
  ShieldAlert,
  History,
  Bell,
  Blocks,
  RefreshCcw,
  BookOpen,
  FlaskRound,
} from 'lucide-react';

export const IconMap: Record<string, any> = {
  'play-circle': PlayCircle,
  zap: Zap,
  lock: Lock,
  'message-square': MessageSquare,
  database: Database,
  mail: Mail,
  globe: Globe,

  workflow: Workflow,
  shuffle: Shuffle,
  bell: Bell,
  history: History,
  gitfork: GitFork,
  shield: ShieldAlert,
  clock: Clock,
  'alert-triangle': AlertTriangle,
  settings: Settings,
  'phone-call': PhoneCall,
  send: Send,
  'message-circle': MessageCircle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  bot: Bot,
  play: Play,
  pause: Pause,
  plus: Plus,
  Plus: Plus,
  edit2: Edit2,
  Save: Save,
  trash2: Trash2,
  Trash2: Trash2,
  blocks: Blocks,
  box: Box,
  tag: Tag,
  code2: Code2,
  users: Users,
  activity: Activity,
  network: Network,
  x: X,
  X: X,
  save: Save,
  power: Power,
  refreshCw: RefreshCcw,
  search: BookOpen,
  flaskround: FlaskRound,
};
export default IconMap;
