export interface ParamTooltipInfo {
  title: string;
  description: string;
}

export const PARAM_TOOLTIPS: Record<string, ParamTooltipInfo> = {
  // LLM Generation Parameters
  temperature: {
    title: 'Temperature',
    description:
      'Controls response randomness and creativity.\n• 0.0 - 0.3: Precise, factual, deterministic (Ideal for RAG & technical docs).\n• 0.7 - 1.0: Creative, varied responses.',
  },
  top_p: {
    title: 'Top-P (Nucleus Sampling)',
    description:
      'Evaluates only top P probability mass tokens.\n• 0.9 = Considers top 90% probable words.\n• Note: Adjust Temperature OR Top-P, not both.',
  },
  system_prompt: {
    title: 'System Prompt',
    description:
      "Global instructions guiding LLM persona and output constraints.\nAvailable placeholders:\n• {context} - Injected vector retrieval context\n• {query} - User's input prompt",
  },
  max_tokens: {
    title: 'Max Generation Tokens',
    description: 'Upper limit on total tokens generated by the LLM in a single response.',
  },
  frequency_penalty: {
    title: 'Frequency Penalty',
    description:
      'Penalizes tokens based on frequency in generated text (-2.0 to 2.0).\nHigher values discourage word repetition.',
  },
  presence_penalty: {
    title: 'Presence Penalty',
    description:
      'Penalizes tokens based on appearance in generated text (-2.0 to 2.0).\nHigher values encourage introducing new topics.',
  },

  // Retrieval & Search Parameters
  approach: {
    title: 'Search Strategy',
    description:
      'Search execution algorithm:\n• Dense (Vector): Semantic embedding match.\n• Sparse (BM25): Exact keyword match.\n• Hybrid: Combines Dense vector + BM25 keyword matching.',
  },
  hybrid_alpha: {
    title: 'Hybrid Alpha Weight',
    description:
      'Weights semantic vs keyword search balance:\n• 1.0 = 100% Vector (Semantic search only)\n• 0.0 = 100% BM25 (Keyword search only)\n• 0.5 = Equal balance (50% Semantic / 50% Keyword)',
  },
  top_k: {
    title: 'Top-K Context Chunks',
    description:
      'Number of highest-ranked document chunks passed into LLM prompt context.\n• Higher K = More background context (Higher token cost & latency).\n• Lower K = Focused context (Faster & lower cost).',
  },
  min_score: {
    title: 'Similarity Score Cutoff',
    description:
      'Minimum relevance score threshold (0.0 to 1.0).\nChunks scoring below threshold are dropped prior to prompt compilation.',
  },
  enable_rrf: {
    title: 'Reciprocal Rank Fusion (RRF)',
    description:
      'Merges and re-ranks dense vector and sparse keyword search results based on rank positions rather than raw distance scores.',
  },
  max_context_tokens: {
    title: 'Max Context Window Tokens',
    description:
      'Maximum token allowance allocated for retrieved context chunks injected into prompt.',
  },

  // Reranking Parameters
  enable_reranking: {
    title: 'Cross-Encoder Reranking',
    description:
      'Applies 2nd-pass deep relevance scoring on candidate chunks.\nSignificantly boosts answer accuracy by filtering out false-positive vector matches.',
  },
  rerank_provider: {
    title: 'Reranker Provider',
    description: 'Cross-encoder scoring engine (e.g. Cohere, BGE, Voyage, Cross-Encoder).',
  },
  rerank_model: {
    title: 'Reranker Model',
    description: 'Cross-encoder model variant optimized for language or domain.',
  },
  candidate_limit: {
    title: 'Initial Candidate Pool Size',
    description:
      'Number of raw candidate chunks retrieved from vector DB before reranking.\nExample: Retrieve top 50 candidates -> Rerank pool -> Pass top 5 to LLM.',
  },

  // Query Settings
  enable_query_rewrite: {
    title: 'Query Expansion & Rewrite',
    description:
      'Uses LLM pre-step to rewrite or expand user query into multi-queries / HyDE (Hypothetical Document Embeddings) before searching vector DB.',
  },
  condense_history: {
    title: 'Condense Chat History',
    description:
      'Summarizes multi-turn conversation history into a standalone self-contained search query.',
  },
};
